This code very fast
ahmetilgin/delta-learning-rule pull request #1
Opened 2017-09-05 03:01 UTC by xiaozhuai

2017-09-05 21:05 UTC, rafaelreinert approved these changes

2017-09-13 12:48 UTC, LauraRozier requested changes
Seems legit to me. 👍
Just fix the comments. :-)

2017-09-13 12:48 UTC, thibmo commented on src/main.cpp
>  #include <iostream>
I doubt you need this, though.

2017-09-13 12:48 UTC, thibmo commented on src/main.cpp
>  using namespace std;
std? Can be removed, too.
Don't want those scary deceases in our code. :(

2017-09-13 12:48 UTC, thibmo commented on src/main.cpp
> +int main(){SinirAgi deltaAgi;deltaAgi.araKatman[0].agirliklariEkrandaGoster();deltaAgi.araKatman[1].agirliklariEkrandaGoster();deltaAgi.cikisKatmani.agirliklariEkrandaGoster();deltaAgi.Sinif[0].bekle
Please remove the spaces, too.

2022-04-19 16:27 UTC, closed without merging